#dictionary etnries for assays (naming conversions)
assay:
    # expected values: "rna_seq", "scrna_seq", "atac_seq", "chip_seq", "scatac_seq", "medip_seq", "mint_chip", "wgbs",
    # "snatac_seq", "snmc_seq", "cytof", "epic"
    rnaseq: rnaseq
    rna-seq: rnaseq
    scrnaseq: scrnaseq
    scrna-seq: scrnaseq
    atacseq: atacseq
    atac-seq: atacseq
    scatacseq: scatacseq
    scatac-seq: scatacseq
    cytof: CyTOF
    methylation: methylome
    epic: methylome
    methylome: methylome
    "methylation_epic": methylome

assay_sub_aliquot_postfix:
    scrnaseq: _1
    scatacseq: _2
    rnaseq: _3
    atacseq: _4
    methylome: _5
    cytof: _6

exposure:
    hiv: HIV
    mrsa: MRSA
    hlth: HLTH
    anth: ANTH

center:
    hi: HI
    du: DU
    pfm: PfM
    ba: BA

specimen_prep:
    pbmc: PBMC
    plasma: Plasma
    paxgenes: PaxGenes

inquiry_file_structure:
    1: exposure
    2: center
    3: specimen_prep
    4: assay